### ISSUE TITLE
Fix the single quote misprediction

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#118]
As shown in @EgorBu's examples, sometimes we predict pair quotes wrong - they do not match, e.g. `'test"` or `"test'`. We need to figure out why and fix this.

**Comment by m09** [comment]
as discussed yesterday in slack, this is closely related to #92 since with correct role information the model should have no problem prediction the correct quote (different quotes have different roles in the pipeline).

**Comment by m09** [comment]
Now that we made progress on role encoding, it appears this class of mistakes might well be different from others. This is from a recent test after role remodeling:
```
Classification report:
             precision    recall  f1-score   support

  <newline>       1.00      1.00      1.00     13377
   <+space>       1.00      0.99      1.00      5849
   <-space>       1.00      0.95      0.97      5849
          '       1.00      0.99      0.99      5674
          "       0.77      0.94      0.84       216
     <noop>       1.00      1.00      1.00    126472
```

Here we can see that we have only 216 double quotes in the project, compared to the 5674 single quotes. That makes the double quotes prediction super error-prone since the support is so brittle. We'd therefore might need some special post-processing for those two classes (based on support, confidence of rules, etc).

**Comment by vmarkovtsev** [comment]
@m09 We need to analyze the single quotes in this example ofc, but most likely we should always predict the dominating quote unless there are super confident counter rules.

**Comment by m09** [comment]
I agree. And we can postprocess `StringLiteral`-s to achieve so if the model fails to always be consistent even though it's super ad-hoc.

**Comment by vmarkovtsev** [comment]
We still mispredict quotes as Egor chosed on ML planning. We will OHE them.

**Comment by zurk** [comment]
@vmarkovtsev let reassign @EgorBu since he is going to implement it?

**Comment by vmarkovtsev** [comment]
Indeed, thanks @zurk

**Comment by vmarkovtsev** [comment]
Current approach: we remove the quote from the right if we predict the left one but we don' t do anything otherwise so the problem may still appear.
The best solution seems to be the removal of the quote feature on the left when we predict the one on the right.
