### ISSUE TITLE
Resolve the security issue warning

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#244]
We need to update Bootstrap or do smth else to get rid of

![screen shot 2018-10-18 at 10 54 41](https://user-images.githubusercontent.com/2793551/47143002-7dc0a400-d2c4-11e8-86f3-8a8d01339ed5.png)

**Comment by m09** [comment]
I don't see it for some reason and when I go to Insights > Dependency Graph > Dependencies, there is no alert :(. Can you screenshot the security alter itself?

**Comment by vmarkovtsev** [comment]
@m09 https://github.com/src-d/style-analyzer/network/alert/lookout/style/format/visualizer/package-lock.json/bootstrap/open

![screen shot 2018-10-18 at 11 56 46](https://user-images.githubusercontent.com/2793551/47146715-edd32800-d2cc-11e8-9221-c9a061c203b3.png)

**Comment by m09** [comment]
Since we use https://react-bootstrap.github.io/ that doesn't support bootstrap v4 yet (it should come in a near future though) and since we won't expose this app publicly I think we should just dismiss the warning.

+ I don't even think it applies since I don't think I use any package that depends on scrollspy.
