### ISSUE TITLE
Harmonize indentation increase and decrease

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#270]
-indent are put at the start of the line, +indent are put after the initial space. It makes more sense to have +indent put at the start of the line also, especially since we pack consecutive labels: this way they'll be bundled with the newline.

**Comment by zurk** [comment]
@m09 can we actually put both after the initial space if there is no big difference for you?
It will be easier to generate a new line (with all fixes we propose) because for example for `VirtualNode` with predicted `y=<-indent>` you can insert `\b` to remove one. In case we have the initial spaces not at the beginning of the line, it is not so simple.

**Comment by m09** [comment]
I'm not sure it's easier. With the -indent before you just skip the first n indent characters, it's even simpler than writing something afterwards :)

It also makes more sense when visualizing or writing rules so I'd rather keep it this way if there is no other reason to change.
