### ISSUE TITLE
Rename benchmark metric names

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#333]
After discussion with the team, it is clear that we should name metrics in https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/benchmarks/evaluate_smoke.py in a better way.

Some of us prefer statistic style: false positive, false negative, etc. But also it is important to have human friendy `detected_wrong_fix` names. So it is good to have a class with all necessary names as properties. 

The same relates to quality report and to a smoke report.

**Comment by warenlg** [comment]
I also assigned myself here because I'm dealing with this issue when refreshing the noisy quality report generation after the paper rush, e.g. recall -> ppcr -> PredR etc https://github.com/src-d/style-analyzer/pull/591

**Comment by zurk** [comment]
@warenlg I think you misunderstand [the original issue](https://github.com/src-d/style-analyzer/issues/333#issue-383039075), because there is no changes in smoke evaluation part, so nothing related to this issue.

**Comment by warenlg** [comment]
No, I perfectly understood the issue. You named it "Rename benchmark metrics", and not "Rename benchmark metrics in smoke", we use different benchmark metrics in smoke, noisy, and general report. In the PR https://github.com/src-d/style-analyzer/pull/591 I changed and renames the metrics used in the noisy report, that's why I said that it "partially fix the issue" https://github.com/src-d/style-analyzer/pull/591#issue-251180639
I just wanted to avoid to have 1000 issues opened and tried to gather them a bit when they deal about the same stuff, nothing more.

**Comment by zurk** [comment]
ok, I updated issue description because it was misleading when we include rest reports here.
