### ISSUE TITLE
Test and fix CodeGenerator for mixed indentation

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#341]
It is not implemented and CodeGenerator behavior is undefined. 

Looks like @warenlg face this issue in https://github.com/src-d/style-analyzer/issues/338#issuecomment-440917641.
Waren, please share details in this issue when you have time.

**Comment by warenlg** [comment]
I think I see couple of bugs here:
1.  currently the `apply_predicted_y` method returns the input sequence of vnodes without any adjusted labels. I believe this comes from a bug in `_iterate_vnodes`. I think because we miss the incrementation of `y_index` here https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/code_generator.py#L204
2.  As I said this week, the code generation looks in trouble with mixed indentation. For example, when processing the file `xhr.js` in https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/tests/jquery_noisy.tar.xz with the model https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/tests/model_jquery.asdf, the code generator returns for the prediction line 10-11 `*** lookout.style.format.code_generator.CodeGenerationError: Indentation decrease excess.` whereas it should returns `try {\n\t\treturn`
3.  For the prediction line 11-12, it returns `;\n\t    } catch` whereas it should returns `;\n\t} catch`

![bug1](https://user-images.githubusercontent.com/24694845/48964593-44f2a980-efab-11e8-8c88-a1c6a158ea6c.png)

**Comment by vmarkovtsev** [comment]
@zurk Status?

**Comment by warenlg** [comment]
This issue is not a bottleneck for the release, at least to me

**Comment by vmarkovtsev** [comment]
Done
