### ISSUE TITLE
Upgrade the deployment scripts

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#568]
There is a better docker compose template in https://github.com/src-d/lookout-sdk-ml/tree/master/lookout/core/container - we should copy swagger from it and the files nearby.

**Comment by vmarkovtsev** [comment]
The major one is with the usage of `sleep` to ensure the startup sequence which I successfully fixed with port/postgres polling.

**Comment by rporres** [comment]
> My talk on MLonCode meetup in front of tens of people online, around 50th minute

Any available logs?

**Comment by vmarkovtsev** [comment]
@rporres Here https://youtu.be/ixxYwcLdkfI?t=3071

The analyzer took more than 5 seconds to start due to Zoom CPU overload and the whole thing broke.

**Comment by meyskens** [comment]
@vmarkovtsev if we understand it correctly you want the Helm chart to work the same as the docker compose file? However we have been unable to find the compose file.

**Comment by vmarkovtsev** [comment]
It's here: https://github.com/src-d/lookout-sdk-ml/tree/master/lookout/core/container

**Comment by rporres** [comment]
This looks like a docker-compose issue rather than a kubernetes one. If the database is not ready for any reason and style analyzer crashes retries will be handled by kubernetes.

There have been recently downtimes in staging style analyzer, but they were related to changes in the args parsing. See https://github.com/src-d/charts/pull/160

Feel free to open this if you see any issue in kubernetes deployment via Helm
